pw_qcm_homepage:
    path:     /qcm
    defaults:
        _controller: PWQCMBundle:QCM:index

pw_qcm_add:
    path:     /qcm/add
    defaults:
        _controller: PWQCMBundle:QCM:add

pw_qcm_view:
    path:     /qcm/view/{id}
    defaults:
        _controller: PWQCMBundle:QCM:view
    requirements:
        id: \d+

pw_qcm_edit:
    path:     /qcm/edit/{id}
    defaults:
        _controller: PWQCMBundle:QCM:edit
    requirements:
        id: \d+

pw_qcm_valider:
    path:     /qcm/valider/{id}
    defaults:
        _controller: PWQCMBundle:QCM:valider
    requirements:
        id: \d+

pw_qcm_delete:
    path:     /qcm/delete/{id}
    defaults:
        _controller: PWQCMBundle:QCM:delete
    requirements:
        id: \d+

pw_qcm_home_qcmgroup:
    path:     /qcmgroup
    defaults:
        _controller: PWQCMBundle:QCMGroup:index

pw_qcm_add_qcmgroup:
    path:     /qcmgroup/add
    defaults:
        _controller: PWQCMBundle:QCMGroup:add

pw_qcm_view_qcmgroup:
    path:     /qcmgroup/view/{id}
    defaults:
        _controller: PWQCMBundle:QCMGroup:view
    requirements:
        id: \d+

pw_qcm_edit_qcmgroup:
    path:     /qcmgroup/edit/{id}
    defaults:
        _controller: PWQCMBundle:QCMGroup:edit
    requirements:
        id: \d+

pw_qcm_delete_qcmgroup:
    path:     /qcmgroup/delete/{id}
    defaults:
        _controller: PWQCMBundle:QCMGroup:delete
    requirements:
        id: \d+