homepage:
    path:     /
    defaults:
        _controller: PWQCMBundle:QCM:index

pwqcm:
    resource: "@PWQCMBundle/Resources/config/qcm_routing.yml"
    prefix:   /qcm

pwqcmgroup:
    resource: "@PWQCMBundle/Resources/config/qcmgroup_routing.yml"
    prefix:   /qcmgroup

pwmatiere:
    resource: "@PWQCMBundle/Resources/config/matiere_routing.yml"
    prefix:   /matiere

pwconcours:
    resource: "@PWQCMBundle/Resources/config/concours_routing.yml"
    prefix:   /concours