<?php

namespace PW\QCMBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QCMGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QCMGroupRepository extends EntityRepository
{
}
