<?php

namespace PW\QCMBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * QCMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QCMRepository extends EntityRepository
{
	public function getAllQcm(){
		
		$qb = $this->createQueryBuilder('q')
			;

		return $qb->getQuery()->getResult();;
	}
}
